### PR TITLE
[NO MRG] Test package on Windows

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #62.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by jakirkham** [comment]
Interesting it looks like `pip` runs into [this error during the build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=421123&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f ) actually

```
error: can't copy 'ipyparallel\labextension\static\vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-313cda.e8f82e0a569f9c85299c.js.map': doesn't exist or not a regular file
```

**Comment by jakirkham** [comment]
Retesting with the changes from PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/64 )

**Comment by jakirkham** [comment]
This appears to be working here as well. Not just in the build, but also the package install, which was the issue seen before in issue ( https://github.com/conda-forge/ipyparallel-feedstock/issues/62 )

**Comment by minrk** [comment]
Closing with #64 merged

**Pull request closed without merging**
